services:
  frontend:
    build:
      context: ./frontend 
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: production
    ports:
      - "5173:5173"     
    depends_on:
      - backend           
    networks:
      - app-network

  backend:
    build:
      context: ./backend/demo 
    ports:
      - "8080:8080"  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
